[tools]
bun = "latest"
aube = "latest"
deno = "latest"
viteplus = "latest"
node = "latest"
wrangler = { version = "latest", allow_builds = ["esbuild", "sharp", "workerd"] }

[deps]
bun = { auto = true }
